SW_VERSION_PATH=../sw_version.h
SEC_CONFIG_PATH=../../../../../utilities/python_scripts/secure_image/

.PHONY: generate_ldscripts FORCE

FORCE:

generate_ldscripts : mem.ld sections.ld

# set a default value for (non-DA1470x) build configurations that don't set BUILD_PROCESSOR
ifeq ($(BUILD_PROCESSOR),)
BUILD_PROCESSOR = BUILD_FOR_MAIN_PROCESSOR
endif

%.ld : $(LDSCRIPT_PATH)/%.ld.h
	@echo "Generating $@ ..."
	"$(CC)" -Ddg_configDEVICE=$(DEVICE) -Ddg_configBUILD_FOR_PROCESSOR=$(BUILD_PROCESSOR) -I "$(BSP_CONFIG_DIR)" -I "$(MIDDLEWARE_CONFIG_DIR)" $(PRE_BUILD_EXTRA_DEFS) -imacros "$(APP_CONFIG_H)" $(LD_DEFS) -MMD -MP -MF"$(@:%=%.d)" -MT"$(@)" -E -P -c "$<" -o "$@"

%_secure.img: %.raw.bin
	if [ -f $(SEC_CONFIG_PATH)secure_cfg.xml ] && [ -f $(SEC_CONFIG_PATH)product_keys.xml ]; then \
		echo 'Invoking: Mkimage Prepare Secure SUOTA Image';\
		"$(PYTHON)" "$(SCRIPT)" -q -p "$(REVISION)" --sw_version "$(SW_VERSION_PATH)" -s "$(SEC_CONFIG_PATH)secure_cfg.xml" --prod_keys "$(SEC_CONFIG_PATH)product_keys.xml" $< $@; \
	fi
	@echo ' '

%.img: %.raw.bin
	@echo 'Invoking: Mkimage Prepare SUOTA Image'
	"$(PYTHON)" "$(SCRIPT)" -q -p "$(REVISION)" --sw_version "$(SW_VERSION_PATH)" $< $@
	@echo ' '

-include mem.ld.d
-include sections.ld.d

ibeacon_example.elf : mem.ld sections.ld
