.PHONY: generate_ldscripts FORCE

FORCE:

generate_ldscripts : mem.ld sections.ld

# set a default value for (non-DA1470x) build configurations that don't set BUILD_PROCESSOR
ifeq ($(BUILD_PROCESSOR),)
BUILD_PROCESSOR = BUILD_FOR_MAIN_PROCESSOR
endif

%.ld : $(LDSCRIPT_PATH)/%.ld.h
	@echo "Generating $@ ..."
	"$(CC)" -Ddg_configDEVICE=$(DEVICE) -Ddg_configBUILD_FOR_PROCESSOR=$(BUILD_PROCESSOR) -I "$(BSP_CONFIG_DIR)" -I "$(MIDDLEWARE_CONFIG_DIR)" $(PRE_BUILD_EXTRA_DEFS) -imacros "$(APP_CONFIG_H)" $(LD_DEFS) -MMD -MP -MF"$(@:%=%.d)" -MT"$(@)" -E -P -c "$<" -o "$@"

-include mem.ld.d
-include sections.ld.d

freertos_retarget.elf : mem.ld sections.ld
